name: 'dbt_customer_churn'
version: '1.0.0'

profile: 'dbt_customer_churn'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_customer_churn:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
