name: dbt CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync

      - name: Create dbt profiles.yml
        run: |
          cat > profiles.yml <<'EOF'
          dbt_customer_churn:
            target: dev

            outputs:
              dev:
                type: databricks
                catalog: dev
                schema: analytics
                auth_type: oauth
                host: "{{ env_var('DBT_DATABRICKS_HOST_DEV') }}"
                http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH_DEV') }}"
                client_id: "{{ env_var('DBT_DATABRICKS_CLIENT_ID') }}"
                client_secret: "{{ env_var('DBT_DATABRICKS_CLIENT_SECRET') }}"
          EOF

      - name: dbt debug
        env:
          DBT_DATABRICKS_HOST_DEV: ${{ secrets.DBT_DATABRICKS_HOST_DEV }}
          DBT_DATABRICKS_HTTP_PATH_DEV: ${{ secrets.DBT_DATABRICKS_HTTP_PATH_DEV }}
          DBT_DATABRICKS_CLIENT_ID: ${{ secrets.DBT_DATABRICKS_CLIENT_ID }}
          DBT_DATABRICKS_CLIENT_SECRET: ${{ secrets.DBT_DATABRICKS_CLIENT_SECRET }}
        run: |
          uv run dbt debug \
            --profiles-dir . \
            --target dev

      - name: dbt build - DEV
        env:
          DBT_DATABRICKS_HOST_DEV: ${{ secrets.DBT_DATABRICKS_HOST_DEV }}
          DBT_DATABRICKS_HTTP_PATH_DEV: ${{ secrets.DBT_DATABRICKS_HTTP_PATH_DEV }}
          DBT_DATABRICKS_CLIENT_ID: ${{ secrets.DBT_DATABRICKS_CLIENT_ID }}
          DBT_DATABRICKS_CLIENT_SECRET: ${{ secrets.DBT_DATABRICKS_CLIENT_SECRET }}
        run: |
          uv run dbt build \
            --profiles-dir . \
            --target dev