name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install dbt dependencies
        run: uv run dbt deps --profiles-dir .

      - name: dbt build - DEV
        env:
          DATABRICKS_HOST: ${{ secrets.DBT_DATABRICKS_HOST_DEV }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DBT_DATABRICKS_HTTP_PATH_DEV }}
        run: |
          uv run dbt build \
            --profiles-dir . \
            --target dev